config/routes.rb
Rails.application.routes.draw do
  resources :zeppelins, only: %i[index show new create] do
    resources :bookings, only: %i[new create]
  end

  resources :bookings, only: %i[show destroy] do 
    member do                             
      get 'confirm'                          
    end
  end

  resources :users, only: [] do
    collection do
      get 'profile', to: 'users#show'
    end
  end

  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class BookingDateValidator < ActiveModel::Validator
  def validate(record)
    unless (record.zeppelin.start_date..record.zeppelin.end_date).include?(record.booking_date)
      record.errors[:booking_date] << "Must be between #{record.zeppelin.start_date} and #{record.zeppelin.end_date}"
    end
  end
end

class Booking < ApplicationRecord
  include ActiveModel::Validations
  belongs_to :zeppelin
  belongs_to :user

  validates_with BookingDateValidator
  validates :zeppelin_id, presence: true, uniqueness: { scope: :booking_date }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookings, dependent: :destroy
  has_many :zeppelins, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/zeppelin.rb
class Zeppelin < ApplicationRecord
  belongs_to :user
  has_one_attached :photo

  validates :name, presence: true
  validates :location, presence: true
  validates :price, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  def self.search(search)
    if search
      Zeppelin.near(search[:location], 30)
    else
      Zeppelin.all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :truc

  def truc
    puts ENV["RAILS_ENV"]
  end
end

app/controllers/bookings_controller.rb
require 'date'

class BookingsController < ApplicationController
  before_action :set_booking, only: %i[destroy show confirm]

  def show
  end

  def new
    @zeppelin = Zeppelin.find(params[:zeppelin_id])
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.zeppelin = Zeppelin.find(params[:zeppelin_id])
    @booking.user = current_user
    if @booking.save
      redirect_to booking_path(@booking)
      UserMailer.with(user: current_user,booking: @booking).reserve_email.deliver_now
      UserMailer.with(user: current_user,booking: @booking).booking_email.deliver_now
    else
    end
  end

  def destroy
    @booking.destroy
    redirect_to profile_users_path
  end

  def confirm
    @booking.status = true
    @booking.save
    UserMailer.with(user: current_user,booking: @booking).confirm_user.deliver_now
    redirect_to booking_path(@booking)
  end

  private

  def booking_params
    params.require(:booking).permit(:zeppelin_id, :user_id, :booking_date)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  layout "homeLayout"
  def home
    @zeppelins = Zeppelin.find([1,2,3])
    @homepage = true
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    if current_user
      @user = current_user
    else
      redirect_to new_user_session_path, notice: 'You are not logged in.'
    end
  end
end

app/controllers/zeppelins_controller.rb
class ZeppelinsController < ApplicationController
  before_action :set_zeppelin, only: %i[show]

  def index
    @zeppelins = Zeppelin.search(params[:search])
    @markers = @zeppelins.map do |zeppelin|
      {
        lat: zeppelin.latitude,
        lng: zeppelin.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { zeppelin: zeppelin }),
        image_url: helpers.asset_url('Zep.svg')

      }
    end
  end

  def show
    @booking = Booking.new
    @zeppelin_bookings = []
    Booking.where(:zeppelin_id == @zeppelin).each { |booking| @zeppelin_bookings << booking.booking_date }
    @markers = [{
                lat: @zeppelin.latitude,
                lng: @zeppelin.longitude,
                infoWindow: render_to_string(partial: "info_window", locals: { zeppelin: @zeppelin }),
                image_url: helpers.asset_url('Zep.svg')
               }]
  end

  def new
    @zeppelin = Zeppelin.new
  end

  def create
    @zeppelin = Zeppelin.new(zeppelin_params)
    @zeppelin.user = current_user
    @zeppelin.save!
    redirect_to zeppelins_path
  end

  private

  def set_zeppelin
    @zeppelin = Zeppelin.find(params[:id])
  end
  # setting strong params
  def zeppelin_params
    params.require(:zeppelin).permit(:name, :location, :price, :start_date, :end_date, :photo)
  end

  def search_params
    params.permit(:location)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_photo(user, size=40)
    if user.photo.attached?
      user.photo.variant(resize: "#{size}x#{size}!")
    else
      gravatar_image_url(user.email, size: size)
    end
  end
end

app/views/bookings/_card.html.erb
<!-- TEST CODE -->
<%= link_to booking_path(booking), class: "book-card-link" do %>
<div class="card-product">
  <div class="image" style="background-image: url(<%= cl_image_path booking.zeppelin.photo.key if booking.zeppelin.photo.attached?%>);">
  </div>
  <div class="infos">
    <div class="zep-name">
      <h2><%= booking.zeppelin.name %></h2>
    </div>
    <div class="card-product-infos">
      <div class="book-date">
        <p><%= booking.booking_date %></p>
      </div>
      <div class="price">
        <p><%= booking.zeppelin.price %><i class="material-icons"> euro_symbol </i></p>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/bookings/new.html.erb
<div class="container">
  <%= simple_form_for [@zeppelin, @booking] do |f| %>
  <%= f.input :booking_date %>
  <%= f.submit %>
  <% end %>
  <p>Your total will be : €<%= @zeppelin.price %> </p>
</div>

app/views/bookings/show.html.erb
<div class="booking-content">
    <div class="booking-header">
        <h2>Booking n°<%= @booking.id %></h2>
        <p><%= @booking.created_at.strftime("%d/%m/%Y")  %></p>
    </div>
    <div class="zeppelin-info">
        <div class="zeppelin-info-text">
          <% if @booking.user == current_user || @booking.zeppelin.user == current_user %>
            <h3>Status</h3>
            <p><%= @booking.status == true ? "Confirmed" : "Not confirmed yet" %></p>
            <h3>Zeppelin</h3>
            <p><%= @booking.zeppelin.name %></p>
            <p>Location: <%= @booking.zeppelin.location %></p>
            <h3>Owner</h3>
            <p>Name: <%= @booking.zeppelin.user.name %></p>
            <p>Email: <%= mail_to @booking.zeppelin.user.email %></p>
            <h3>Booking Date</h3>
            <p><%= @booking.booking_date.strftime("%d/%m/%Y") %></p>
            <h3>Booking Price</h3>
            <p><%= @booking.zeppelin.price %>€</p>
            <h3>Renter</h3>
            <p>Name: <%= @booking.user.name %></p>
            <p>Send an e-mail: <%= mail_to @booking.user.email %></p>
        </div>
        <%= cl_image_tag @booking.zeppelin.photo.key, crop: :scale,class:'booking-img' if @booking.zeppelin.photo.attached? %>
        <%= link_to 'Delete Booking', booking_path(@booking),
         method: :delete,
        data: { confirm: "Are you sure?" },class:'delete-booking'  %>
        <% else %>
        <p>Sorry, you are not the owner or the renter.</p>
        <% end %>
    </div>
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="footer-image">
    <%= image_tag "Logo-LentZep.png", height: 30 %>
  </div>
  <div class="footer-copyright">
    © 2020 LentZeppelin, Inc. All rights reserved - Made with <i class="fas fa-heart"></i> by the Lent-Zeppelin Team.
  </div>
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
</div>

app/views/layouts/_not-signed-home.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon-home">
  <div class="navbar-group logo">
    <%= link_to "/", class: "navbar-brand-home" do %>
    <%= image_tag "logo_1.png" %>
    <% end %>
  </div>


  <div class="navbar-group links">
    <% unless @homepage %>
    <div class="dropdown">
      <i class="material-icons dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> search </i>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
        <%= form_for :search, url: zeppelins_path, method: 'get' do |f| %>
        <div class="search-form">
          <%= f.text_field :location, class:'form-control input search', id:'search', placeholder:'Search' %>
          <%= button_tag(class:'btn btn-danger input') do %>
          <i class="material-icons"> search </i>
          <% end %>
        </div>
        <% end %>
      </div>
    </div>
    <% end %>

    <div class="dropdown">
      <i class="material-icons dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> perm_identity </i>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
        <%= link_to "Connexion", new_user_session_path, class: "nav-link" %>
        <%= link_to "Inscription", new_user_registration_path, class: "nav-link" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_not-signed-in-navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="navbar-group logo">
    <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "logo_1.png" %>
    <% end %>
  </div>
  <div class="navbar-group links">
    <% unless @homepage %>
    <div class="dropdown">
      <i class="material-icons dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> search </i>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
        <%= form_for :search, url: zeppelins_path, method: 'get' do |f| %>
        <div class="search-form">
          <%= f.text_field :location, class:'form-control input search', id:'search', placeholder:'Search' %>
          <%= button_tag(class:'btn btn-danger input') do %>
          <i class="material-icons"> search </i>
          <% end %>
        </div>
      <% end %>
      </div>
      <% end %>
      <div class="dropdown">
        <i class="material-icons dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> perm_identity </i>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
          <%= link_to "Connexion", new_user_session_path, class: "nav-link" %>
          <%= link_to "Inscription", new_user_registration_path, class: "nav-link" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_signed-home.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon-home">
  <div class="navbar-group logo">
    <%= link_to "/", class: "navbar-brand-home" do %>
    <%= image_tag "logo_1.png" %>
    <% end %>
  </div>

  <div class="navbar-group links">
    <% unless @homepage %>
    <div class="dropdown">
      <i class="material-icons dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> search </i>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
        <%= form_for :search, url: zeppelins_path, method: 'get' do |f| %>
        <div class="search-form">
          <%= f.text_field :location, class:'form-control input search', id:'search', placeholder:'Search' %>
          <%= button_tag(class:'btn btn-danger input') do %>
          <i class="material-icons"> search </i>
          <% end %>
        </div>
        <% end %>
      </div>
    </div>
    <% end %>

    <div class="dropdown">
      <i class="material-icons dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> perm_identity </i>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
        <%= link_to "Déconnexion", destroy_user_session_path, class: "nav-link", method: :delete %>
        <%= link_to "Profil", profile_users_path, class: "nav-link" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_signed-in-navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">

  <div class="navbar-group logo">
    <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "logo_1.png" %>
    <% end %>
  </div>
    <div class="navbar-group links">
      <% unless @homepage %>
      <div class="dropdown">
        <i class="material-icons dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> search </i>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
          <%= form_for :search, url: zeppelins_path, method: 'get' do |f| %>
          <div class="search-form">
            <%= f.text_field :location, class:'form-control input search', id:'search', placeholder:'Search' %>
            <%= button_tag(class:'btn btn-danger input') do %>
            <i class="material-icons"> search </i>
            <% end %>
          </div>
          <% end %>
        </div>
      </div>
      <% end %>

      <div class="dropdown">
        <i class="material-icons dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> perm_identity </i>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
          <%= link_to "Déconnexion", destroy_user_session_path, class: "nav-link", method: :delete %>
          <%= link_to "Profil", profile_users_path, class: "nav-link" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Lent-Zeppelin</title>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <link rel="icon" href="<%= image_path('Logo-LentZep.png') %> " />
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  <link href='https://api.mapbox.com/mapbox-gl-js/v1.8.1/mapbox-gl.css' rel='stylesheet'>
  <link href="https://fonts.googleapis.com/css?family=Permanent+Marker&display=swap" rel="stylesheet">
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <% if user_signed_in? %>
  <%= render 'layouts/signed-in-navbar' %>
  <% else %>
  <%= render 'layouts/not-signed-in-navbar' %>
  <% end %>

  <%= yield %>

  <%= render 'layouts/footer' %>

  <%= javascript_pack_tag "application" %>
</body>
</html>

app/views/layouts/homeLayout.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Lent-Zeppelin</title>
  <link rel="icon" type="image/png" href="/assets/Logo-LentZep.png" />
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <link rel="icon" href="<%= image_path('Logo-LentZep.png') %> " />
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Permanent+Marker&display=swap" rel="stylesheet">
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <% if user_signed_in? %>
  <%= render 'layouts/signed-home' %>
  <% else %>
  <%= render 'layouts/not-signed-home' %>
  <% end %>

  <%= yield %>

  <%= javascript_pack_tag "application" %>
</body>
</html>

app/views/pages/home.html.erb
<div class="banner">
  <%= form_for :search, url: zeppelins_path, method: 'get' do |f| %>
  <div class="form-group">
    <%= f.text_field :location, class:'form-control input search', placeholder:'Search by location' %>
    <%= f.submit 'Search', class:' btn btn-danger input-2'%>
  </div>
  <% end %>
  <%= link_to 'See all the zeppelins', zeppelins_path, class: 'btn btn-danger' %>
</div>
<div class="container">
  <h1>Trending</h1>
  <%= render 'zeppelins/list', zeppelins:  @zeppelins %>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<!-- TEST CODE -->
<div class="page">

  <div class="middle-board">
    <div class="booking">
      <h3><i class="far fa-calendar-alt"></i> - My bookings</h3>
      <div class="book-cards">
        <% @user.bookings.each do |booking| %>
        <%= render 'bookings/card', booking: booking %>
        <% end %>
      </div>
    </div>
    <h3>My zeppelins</h3>
    <div class="zeppelins">
      <% @user.zeppelins.each do |zeppelin| %>
      <%= render 'zeppelins/card', zeppelin: zeppelin %>
      <% end %>
    </div>
  </div>
  <div class="right-board">
    <div class="action-button">
      <h4><%= link_to "Add zeppelin", new_zeppelin_path %></h4>
    </div>
    <p>A Zeppelin is a type of rigid airship named after the German Count Ferdinand
        von Zeppelin (German pronunciation: [ˈt͡sɛpəliːn]) who pioneered rigid airship development
        at the beginning of the 20th century. Zeppelin's notions were first formulated
        in 1874[1] and developed in detail in 1893.[2] They were patented in Germany in 1895
        and in the United States in 1899.[3] After the outstanding success of the Zeppelin
        design, the word zeppelin came to be commonly used to refer to all rigid airships.
        Zeppelins were first flown commercially in 1910 by Deutsche Luftschiffahrts-AG (DELAG),
        the world's first airline in revenue service. By mid-1914, DELAG had carried over 10,000
        fare-paying passengers on over 1,500 flights. During World War I, the German
        military made extensive use of Zeppelins as bombers and scouts, killing over
        500 people in bombing raids in Britain.
      </p>
  </div>
</div>

app/views/zeppelins/_card.html.erb
<%= link_to zeppelin_path(zeppelin), class: "zep-card-link" do %>
<div class="zeppelin-card">
  <div class="zeppelin-img" style="background-image: url(<%= cl_image_path zeppelin.photo.key if zeppelin.photo.attached?%>);">
  </div>
  <div class="zeppelin-info">
    <div class="zeppelin-name"><%= zeppelin.name %></div>
    <div class="zeppelin-price"><%= zeppelin.price %><i class="material-icons"> euro_symbol </i></div>
    <div class="description"> <%= zeppelin.description %> </div>
  </div>
  <!--  <%= link_to "Book now", new_zeppelin_booking_path(zeppelin), class: 'btn btn-danger'  %> -->
</div>
<% end %>

app/views/zeppelins/_form.html.erb
<%= simple_form_for @zeppelin do |f| %>
  <%= f.input :name %>
  <%= f.input :location, input_html: { class: "search" } %>
  <%= f.input :price %>
  <%= f.input :start_date %>
  <%= f.input :end_date %>
  <%= f.input :photo, as: :file %>
  <%= f.submit class: "btn btn-primary form-btn" %>
<% end %>

app/views/zeppelins/_info_window.html.erb
<div class="popup" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path zeppelin.photo.key if zeppelin.photo.attached? %> );">
  <h2><%= zeppelin.name %></h2>
  <p><%= zeppelin.price %>€</p>
  <% if current_page?(zeppelin_path(zeppelin)) %>
  <% if user_signed_in? %>
  <button type="button" class="btn btn-primary book-button" data-toggle="modal" data-target="#exampleModal">
    Book now
  </button>
  <% end %>
  <% else %>
  <%= link_to 'More info', zeppelin_path(zeppelin), class: 'btn btn-primary book-button' %>
  <% end %>
</div>

app/views/zeppelins/_list.html.erb
<div class="cards-container">
  <% zeppelins.each do |zeppelin| %>
  <%= render 'zeppelins/card', zeppelin: zeppelin %>
  <% end %>
</div>

app/views/zeppelins/index.html.erb
<% unless @zeppelins.empty? %>
<div
id="map"
class="map-index"
data-markers="<%= @markers.to_json %>"
data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
></div>
<% end %>
<div class="container">
  <h1>Results</h1>
  <% if @zeppelins.empty? %>
  <p>Sorry! There are no zeppelins available for this location.</p>
  <% else %>
  <%= render 'list', zeppelins:  @zeppelins %>
  <% end %>
</div>

app/views/zeppelins/new.html.erb
<div class="container" id="form-size">
  <h1>Create a Zeppelin</h1>

  <div class="form">
    <%= render 'form' %>
    <%= link_to "Cancel", zeppelins_path, class: "btn btn-danger form-btn" %>
  </div>
</div>

app/views/zeppelins/show.html.erb
<div class="zeppelin-photo" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path @zeppelin.photo.key, crop: :fill if @zeppelin.photo.attached? %> );">
  <h1>
    <%= @zeppelin.name %>
  </h1>
</div>

<div class="show-zeppelin">
  <div class="zep-cont">
    <h2>Informations :</h2>
    <div class="informations">
      <div class="text-infos">
        <p><i class="fas fa-map-marker-alt"></i> - <strong>Location</strong> : <%= @zeppelin.location %></p>
        <p><i class="fas fa-coins"></i> - <strong>Price/day</strong> : <%= @zeppelin.price %> €</p>
        <% if @zeppelin.start_date.day < @zeppelin.end_date.day %>
        <p><i class="fas fa-calendar-alt"></i> - Book this zeppelin between the <strong><%= @zeppelin.start_date %> of <%= @zeppelin.end_date.strftime("%B") %></strong> and the <strong><%= @zeppelin.end_date %> of <%= @zeppelin.end_date.strftime("%B") %></strong></p>
        <% else %>
        <p><i class="fas fa-calendar-alt"></i> - Book this zeppelin between <strong> <%= @zeppelin.start_date.day %> of <%= @zeppelin.start_date.strftime("%B") %></strong> and the <strong><%= @zeppelin.end_date.day %> of <%= @zeppelin.end_date.strftime("%B") %></strong></p>
        <% end %>
      </div>
      <!-- Button trigger modal -->
      <% if user_signed_in? %>
      <button type="button" class="btn btn-danger book-button" data-toggle="modal" data-target="#exampleModal">
        Book now
      </button>
      <% end %>
    </div>
  </div>
  <div
  id="map"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  ></div>
</div>
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Book <%= @zeppelin.name %> </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for [@zeppelin, @booking] do |f| %>
        <%= f.error_notification %>
        <%#= hidden_field_tag 'minDate', @zeppelin.start_date %>
        <%#= hidden_field_tag 'maxDate', @zeppelin.end_date %>
        <%#= hidden_field_tag 'alreadyBooked', @zeppelin_bookings %>

        <input type="text" id="datePicker" placeholder="Select your booking date" name="booking[booking_date]" data-input data-minDate="<%= @zeppelin.start_date %>" data-maxDate="<%= @zeppelin.end_date %>" data-bookingsDate="<%= @zeppelin_bookings.to_json %>">
        <p>Your total will be : €<%= @zeppelin.price %> </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= f.submit 'Book now', class: 'btn btn-danger' %>
        <% end %>
      </div>

    </div>
  </div>
</div>